# Generated by Django 5.2.5 on 2025-09-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='email',
            new_name='user',
        ),
    ]
