# Generated by Django 5.2.5 on 2025-09-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_sectionclass_teacher_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
