# Generated by Django 5.2.5 on 2025-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_teacher_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionclass',
            name='day',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=3),
        ),
    ]
