# Generated by Django 5.2.6 on 2025-10-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='start_year',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
