# Generated by Django 5.2.7 on 2025-10-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='enroll',
            field=models.BooleanField(default=False),
        ),
    ]
