# Generated by Django 5.2.6 on 2025-10-26 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='personnels.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student', 'course')},
        ),
    ]
