# Generated by Django 5.2.7 on 2025-10-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_teachers_course_professors'),
        ('enrollments', '0002_alter_enroll_date'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student', 'section')},
        ),
    ]
