# Generated by Django 5.2.7 on 2025-10-25 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_teachers_course_professors'),
        ('enrollments', '0003_alter_enroll_unique_together'),
        ('personnels', '0005_remove_registra_id_alter_registra_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('enroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enrollments.enroll')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('score3', models.IntegerField(default=0)),
                ('score4', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enroll',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student', 'course')},
        ),
    ]
