# Generated by Django 5.2.6 on 2025-10-04 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEnrollQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('C+', 'C+'), ('D+', 'D+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=3)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
    ]
