"""
Django settings for CloudProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q)(&neeza#mq*x62nf9t7=xbi0+=z#2%-fu$qrf&p(gjhkd1wc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'authen',
    'users',
    'academics',
    'enrollment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authen.middleware.RequireLoginMiddleware',
]

ROOT_URLCONF = 'CloudProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                "authen.context_processors.current_user",
            ],
        },
    },
]

WSGI_APPLICATION = 'CloudProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'register',
    #     'USER': 'postgres',
    #     'PASSWORD': 'postgres_2547',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    # }
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'register',
            'USER': 'root',
            'PASSWORD': 'Cloud_rds_1234',
            'HOST': 'cloud-project-rds.cpikuy4u2d65.us-east-1.rds.amazonaws.com',
            'PORT': '5432',
        }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AWS S3 setting
INSTALLED_APPS += ['storages']

AWS_ACCESS_KEY_ID = "ASIAXYKJW6JHDQ7HGZ6A"
AWS_SECRET_ACCESS_KEY = "Yiq76OFPBjHQNVxDFmiX8B9GcjpRNi+6kwzNOO8L"
AWS_STORAGE_BUCKET_NAME = 'cloud-project-registration'
AWS_S3_REGION_NAME = "us-east-1"

# # Static files
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
# # Media files
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

# AWS Cognito setting
COGNITO_USER_POOL_ID = "us-east-1_8tddVcR3w"
COGNITO_APP_CLIENT_ID = "7uvhggam7tq549blqafp21a45a"
COGNITO_REGION = "us-east-1"
COGNITO_APP_CLIENT_SECRET = "1j186e1hujt36l9jrlkgpbaml3d8cock44lu2kiot24pc95hlg0b"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# ตำแหน่ง Base static
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

ALLOWED_HOSTS = ['3.236.194.98']
