# Generated by Django 5.2.7 on 2025-10-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
