# Generated by Django 5.2.7 on 2025-10-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_semester_edit_semester_enroll'),
        ('personnels', '0002_student_enrolled_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.IntegerField()),
                ('pay', models.CharField(choices=[('N', 'ยัง'), ('Y', 'เรียบร้อย')], default='N', max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='departments.department')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='personnels.student')),
            ],
        ),
    ]
