# Generated by Django 5.2.7 on 2025-10-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.CharField(choices=[('N', 'ยัง'), ('W', 'รอตรวจสอบ'), ('Y', 'ยืนยัน')], default='N', max_length=1),
        ),
    ]
