# Generated by Django 5.2.7 on 2025-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0005_remove_registra_id_alter_registra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slip',
            field=models.ImageField(blank=True, null=True, upload_to='slips/'),
        ),
    ]
